services:
  admin-frontend:
    image: ghcr.io/oscar-ekeyekwu/orbtix-admin-frontend:latest
    container_name: orbtix-admin-frontend
    restart: always
    env_file:
      - .env
    ports:
      - "4100:80"
    networks:
      - orbitx-network

networks:
  orbitx-network:
    external: true
